In [63]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB, MultinomialNB
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
from sklearn.neighbors import KNeighborsClassifier

In [6]:
mobile = pd.read_csv(r'C:\Users\karthikp\Downloads\Inceptors\Preprocessing files\Cellphone.csv')

In [21]:
mobile.shape

(2000, 21)

In [7]:
mobile.head

<bound method NDFrame.head of       battery_power  blue  clock_speed  dual_sim  fc  four_g  int_memory  \
0               842     0          2.2         0   1       0           7   
1              1021     1          0.5         1   0       1          53   
2               563     1          0.5         1   2       1          41   
3               615     1          2.5         0   0       0          10   
4              1821     1          1.2         0  13       1          44   
...             ...   ...          ...       ...  ..     ...         ...   
1995            794     1          0.5         1   0       1           2   
1996           1965     1          2.6         1   0       0          39   
1997           1911     0          0.9         1   1       1          36   
1998           1512     0          0.9         0   4       1          46   
1999            510     1          2.0         1   5       1          45   

      m_dep  mobile_wt  n_cores  ...  px_height  px_width

In [9]:
mobile.dtypes

battery_power      int64
blue               int64
clock_speed      float64
dual_sim           int64
fc                 int64
four_g             int64
int_memory         int64
m_dep            float64
mobile_wt          int64
n_cores            int64
pc                 int64
px_height          int64
px_width           int64
ram                int64
sc_h               int64
sc_w               int64
talk_time          int64
three_g            int64
touch_screen       int64
wifi               int64
price_range        int64
dtype: object

In [12]:
mobile['price_range'].unique()

array([1, 2, 3, 0], dtype=int64)

In [27]:
mobile.isnull().sum()

battery_power    0
blue             0
clock_speed      0
dual_sim         0
fc               0
four_g           0
int_memory       0
m_dep            0
mobile_wt        0
n_cores          0
pc               0
px_height        0
px_width         0
ram              0
sc_h             0
sc_w             0
talk_time        0
three_g          0
touch_screen     0
wifi             0
price_range      0
dtype: int64

In [22]:
x = mobile.drop('price_range',1)
x

C:\Users\karthikp\AppData\Local\Temp/ipykernel_14780/1941159814.py:1: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only
  x = mobile.drop('price_range',1)


battery_power  blue  clock_speed  dual_sim  fc  four_g  int_memory  \
0               842     0          2.2         0   1       0           7   
1              1021     1          0.5         1   0       1          53   
2               563     1          0.5         1   2       1          41   
3               615     1          2.5         0   0       0          10   
4              1821     1          1.2         0  13       1          44   
...             ...   ...          ...       ...  ..     ...         ...   
1995            794     1          0.5         1   0       1           2   
1996           1965     1          2.6         1   0       0          39   
1997           1911     0          0.9         1   1       1          36   
1998           1512     0          0.9         0   4       1          46   
1999            510     1          2.0         1   5       1          45   

      m_dep  mobile_wt  n_cores  pc  px_height  px_width   ram  sc_h  sc_w  \
0       0.6        188        2   2         20       756  2549     9     7   
1       0.7        136        3   6        905      1988  2631    17     3   
2       0.9        145        5   6       1263      1716  2603    11     2   
3       0.8        131        6   9       1216      1786  2769    16     8   
4       0.6        141        2  14       1208      1212  1411     8     2   
...     ...        ...      ...  ..        ...       ...   ...   ...   ...   
1995    0.8        106        6  14       1222      1890   668    13     4   
1996    0.2        187        4   3        915      1965  2032    11    10   
1997    0.7        108        8   3        868      1632  3057     9     1   
1998    0.1        145        5   5        336       670   869    18    10   
1999    0.9        168        6  16        483       754  3919    19     4   

      talk_time  three_g  touch_screen  wifi  
0            19        0             0     1  
1             7        1             1     0  
2             9        1             1     0  
3            11        1             0     0  
4            15        1             1     0  
...         ...      ...           ...   ...  
1995         19        1             1     0  
1996         16        1             1     1  
1997          5        1             1     0  
1998         19        1             1     1  
1999          2        1             1     1  

[2000 rows x 20 columns]

In [24]:
y = mobile.iloc[:,-1]
y

0       1
1       2
2       2
3       2
4       1
       ..
1995    0
1996    2
1997    3
1998    0
1999    3
Name: price_range, Length: 2000, dtype: int64

In [100]:
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.25,random_state=7)

In [101]:
model = GaussianNB()

In [102]:
model.fit(x_train, y_train)

GaussianNB()

In [103]:
y_pred = model.predict(x_test)

In [104]:
Gaus_acc_score = accuracy_score(y_test, y_pred)

In [105]:
print(Gaus_acc_score)

0.804


In [106]:
model1 = MultinomialNB()

In [107]:
model1.fit(x_train, y_train)

MultinomialNB()

In [108]:
y_pred = model1.predict(x_test)

In [109]:
MN_acc_score = accuracy_score(y_test, y_pred)

In [110]:
print(MN_acc_score)

0.55


In [62]:
print(confusion_matrix(y_test, y_pred))

[[122  30   9   1]
 [ 27  55  38  24]
 [  8  35  48  63]
 [  0  15  32  93]]


In [61]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.78      0.75      0.76       162
           1       0.41      0.38      0.39       144
           2       0.38      0.31      0.34       154
           3       0.51      0.66      0.58       140

    accuracy                           0.53       600
   macro avg       0.52      0.53      0.52       600
weighted avg       0.52      0.53      0.52       600



In [111]:
knn_test = KNeighborsClassifier(n_neighbors = 25)

In [112]:
knn_test.fit(x_train, y_train)

KNeighborsClassifier(n_neighbors=25)

In [113]:
y_pred = knn_test.predict(x_test)

In [114]:
KNN_acc_score = accuracy_score(y_test, y_pred)

In [115]:
print(KNN_acc_score)

0.94


In [126]:
if MN_acc_score > KNN_acc_score and MN_acc_score > Gaus_acc_score:
    print('MN_acc_score seem to have good accuracy')
elif KNN_acc_score > MN_acc_score and KNN_acc_score > Gaus_acc_score:
    print('KNN_acc_score seem to have good accuracy')
else:
    print('Gaus_acc_score seem to have good accuracy')

KNN_acc_score seem to have good accuracy
