In [1]:
import numpy as np
import pandas as pd

In [2]:
array1 = np.array([1,2,3,4])
array1

array([1, 2, 3, 4])

In [6]:
print(array1.ndim)
print(array1.shape)
type(array1)

1
(4,)


numpy.ndarray

In [14]:
array2 = np.array([[5,6,7,8],[9,10,11,12],[13,14,15,16]])
print(array2.ndim)
print(array2.shape)
type(array2)

2
(3, 4)


numpy.ndarray

In [21]:
array3 = np.array([[20,21,22,23],[24,25,26,27]], dtype = float)
array3

array([[20., 21., 22., 23.],
       [24., 25., 26., 27.]])

In [26]:
array2 = np.array([[5,6,7,8],[9,10,11,12],[13,14,15,16]])
print(array2)
print(array2.shape)

[[ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
(3, 4)


In [27]:
print(array2.shape)

(3, 4)


In [36]:
array2=array2.reshape(1,12)
print(array2)

[[ 5  6  7  8  9 10 11 12 13 14 15 16]]


In [43]:
array5 = np.array([[1,2,3,4,5],[4,5,6,7,8],[1.2,3.4,5.6,7.8,9.1],[4,4,4,5,5]], dtype=int)
array5

array([[1, 2, 3, 4, 5],
       [4, 5, 6, 7, 8],
       [1, 3, 5, 7, 9],
       [4, 4, 4, 5, 5]])

In [54]:
array6 = np.ones([6,7])
array6

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

In [60]:
x1=([1,2,3],[4,5,6])
print(np.array(x1))
print(np.asarray(x1))

[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]]


In [61]:
type(x1)

tuple

In [66]:
x2 = [[1,2,3,4],[5,6,7,8]]
print(np.array(x2))

[[1 2 3 4]
 [5 6 7 8]]


In [67]:
type(x2)

list

In [71]:
x3 = np.arange(2,10,2)
x3

array([2, 4, 6, 8])

In [85]:
x3 = np.linspace(1,20,6)
x3

array([ 1. ,  4.8,  8.6, 12.4, 16.2, 20. ])

In [97]:
a1 = np.arange(50)
a2=slice(1,30,5)
print(a1[a2])

[ 1  6 11 16 21 26]


In [108]:
a2=np.linspace(1,30,6)
a2

array([ 1. ,  6.8, 12.6, 18.4, 24.2, 30. ])

In [10]:
list1=np.arange(10)
a3=list1[:-2]
a3

array([0, 1, 2, 3, 4, 5, 6, 7])

In [14]:
list1 = np.arange(10)
arr1 = slice(2,9,2)
list1[arr1]

array([2, 4, 6, 8])

In [17]:
arr1 = np.array([[1,2,3],[2,3,4],[4,5,6]])
arr1

array([[1, 2, 3],
       [2, 3, 4],
       [4, 5, 6]])

In [20]:
a = arr1[[0,1,2],[2,1,0]]
a

array([3, 3, 4])

In [27]:
a=arr1[[0]]
b=a[1:]
print(b)

[]


In [28]:
arr2 = np.array([[1,2,np.nan,4,5,6],[7,8,9,np.nan,11,12]])
arr2

array([[ 1.,  2., nan,  4.,  5.,  6.],
       [ 7.,  8.,  9., nan, 11., 12.]])

In [34]:
arr2[np.isnan(arr2)]

array([nan, nan])

In [35]:
arr1

array([[1, 2, 3],
       [2, 3, 4],
       [4, 5, 6]])

In [43]:
b = arr1[1:1,2:2]
print(b)

[]


In [45]:
a1 = np.array([[1,2,3, 5, np.nan, 9],[4, 5,6, 1,2,3],[7,8, 9, 5,6, 1],[10,np.nan,12, 9, 5,6]])
a1

array([[ 1.,  2.,  3.,  5., nan,  9.],
       [ 4.,  5.,  6.,  1.,  2.,  3.],
       [ 7.,  8.,  9.,  5.,  6.,  1.],
       [10., nan, 12.,  9.,  5.,  6.]])

In [53]:
z = a1[5:2]
z

array([], shape=(0, 6), dtype=float64)

In [64]:
z = a1[:3]
z

array([[ 1.,  2.,  3.,  5., nan,  9.],
       [ 4.,  5.,  6.,  1.,  2.,  3.],
       [ 7.,  8.,  9.,  5.,  6.,  1.]])

In [8]:
x1 = np.array([[88,99],[10,20],[24,45]])
x2 = np.array([[5,6],[10,12],[11,12]])
z = x1 * x2
z

array([[440, 594],
       [100, 240],
       [264, 540]])

In [10]:
a = np.array([1, 2, 3])
b = np.array([2, 3, 4])
z = np.stack((b,a))
z

array([[2, 3, 4],
       [1, 2, 3]])

In [17]:
print(x1)
print(x2)

[[88 99]
 [10 20]
 [24 45]]
[[ 5  6]
 [10 12]
 [11 12]]


In [14]:
np.stack((x1,x2), axis=1)

array([[[88, 99],
        [ 5,  6]],

       [[10, 20],
        [10, 12]],

       [[24, 45],
        [11, 12]]])

In [15]:
np.vstack((x1,x2))

array([[88, 99],
       [10, 20],
       [24, 45],
       [ 5,  6],
       [10, 12],
       [11, 12]])

In [16]:
np.hstack((x1,x2))

array([[88, 99,  5,  6],
       [10, 20, 10, 12],
       [24, 45, 11, 12]])

In [20]:
x3 = np.arange(10)
a = np.split(x3,2)
a

[array([0, 1, 2, 3, 4]), array([5, 6, 7, 8, 9])]

In [24]:
np.append(x1,x2, axis = 0)


array([[88, 99],
       [10, 20],
       [24, 45],
       [ 5,  6],
       [10, 12],
       [11, 12]])

In [26]:
np.delete(x2,1)

array([ 5, 10, 12, 11, 12])

In [27]:
x2

array([[ 5,  6],
       [10, 12],
       [11, 12]])

In [32]:
np.delete(x2,3)

array([ 5,  6, 10, 11, 12])

In [33]:
np.delete(x1,2)

array([88, 99, 20, 24, 45])

In [51]:
print(np.hstack(x1))
print(np.hstack(x2))

[88 99 10 20 24 45]
[ 5  6 10 12 11 12]


In [55]:
np.sum((x1,x2), axis=1)

array([[122, 164],
       [ 26,  30]])

np.median((x1),axis=0)

In [59]:
x1

array([[88, 99],
       [10, 20],
       [24, 45]])

In [62]:
np.mean((x1),axis=0)

array([40.66666667, 54.66666667])

In [65]:
x1

array([[88, 99],
       [10, 20],
       [24, 45]])

In [79]:
x4=np.append(x1,x2,axis=1)
x4

array([[88, 99,  5,  6],
       [10, 20, 10, 12],
       [24, 45, 11, 12]])

In [86]:
x4[2:3]

array([[24, 45, 11, 12]])

In [87]:
import pandas as pd

In [93]:
x1 = np.array([1,2,3,4])
x2 = pd.Series(x1, index=[1,2,3,4])
x2

1    1
2    2
3    3
4    4
dtype: int32

In [99]:
dict1 = {'first':'Value 1', 'Second':'Value 2'}
x3 = pd.Series(dict1)
x3

first     Value 1
Second    Value 2
dtype: object

In [104]:
x3[1]

'Value 2'

#### Pandas

In [106]:
l = [1,2,3,4,5,6]
x1=pd.Series(l)
x1

0    1
1    2
2    3
3    4
4    5
5    6
dtype: int64

In [108]:
l = [1,2,3,4,5,6]
x1=pd.Series(l, index=['a','b','c','d','e','f'])
x1

a    1
b    2
c    3
d    4
e    5
f    6
dtype: int64

In [12]:
d = {'Name':['Sathya','Deeksha','Thiyas'],'Relationship':['Spouse','Daughter','Son'],'Age':[37,10,1],
     'Sex':['F','F','M'],'Color':['White','Dark','Dark']}
x2=pd.DataFrame(d)
x2

Name Relationship  Age Sex  Color
0   Sathya       Spouse   37   F  White
1  Deeksha     Daughter   10   F   Dark
2   Thiyas          Son    1   M   Dark

In [114]:
x3 = ['Name','Relationship']
x3

['Name', 'Relationship']

In [115]:
x2[x3]

Name Relationship
1   Sathya       Spouse
2  Deeksha     Daughter
3   Thiyas          Son

In [117]:
x4 = ['Name','Age']
x2[x4]

Name  Age
1   Sathya   37
2  Deeksha   10
3   Thiyas    1

In [80]:
l1=[['Sathya','Spouse','37'],['Deeksha','Daughter','10'],['Thiyas','Son',1]]
l2=pd.DataFrame(l1,columns=['Name','Relation','Age'],index=['a','b','c'])
l2

Name  Relation Age
a   Sathya    Spouse  37
b  Deeksha  Daughter  10
c   Thiyas       Son   1

In [126]:
x2

Name Relationship  Age Sex  Color
1   Sathya       Spouse   37   F  White
2  Deeksha     Daughter   10   F   Dark
3   Thiyas          Son    1   M   Dark

In [6]:
x1=x2[['Name','Relationship']]
x1

Name Relationship
1   Sathya       Spouse
2  Deeksha     Daughter
3   Thiyas          Son

In [13]:
x2['Lang.']=pd.Series([1,2,3])
x2

Name Relationship  Age Sex  Color  Lang.
0   Sathya       Spouse   37   F  White      1
1  Deeksha     Daughter   10   F   Dark      2
2   Thiyas          Son    1   M   Dark      3

In [20]:
val = x2['Age'].values[0:3]
val = pd.DataFrame(val,columns=['Age'])
val

Age
0   37
1   10
2    1

In [21]:
x2

Name Relationship  Age Sex  Color  Lang.
0   Sathya       Spouse   37   F  White      1
1  Deeksha     Daughter   10   F   Dark      2
2   Thiyas          Son    1   M   Dark      3

In [35]:
x2['Weight']=pd.Series([65,40,10])
x2

Name Relationship  Age Sex  Color  Lang.  Weight  height
0   Sathya       Spouse   37   F  White      1      65     160
1  Deeksha     Daughter   10   F   Dark      2      40     120
2   Thiyas          Son    1   M   Dark      3      10      90

In [36]:
x2['height']=pd.Series([160,120,90])
x2

Name Relationship  Age Sex  Color  Lang.  Weight  height
0   Sathya       Spouse   37   F  White      1      65     160
1  Deeksha     Daughter   10   F   Dark      2      40     120
2   Thiyas          Son    1   M   Dark      3      10      90

In [57]:
x2['h - w']=x2['height'] - x2['Weight']
x2

Name Relationship  Age Sex  Color  Lang.  Weight  height  h - w
0   Sathya       Spouse   37   F  White      1      65     160     95
1  Deeksha     Daughter   10   F   Dark      2      40     120     80
2   Thiyas          Son    1   M   Dark      3      10      90     80

In [40]:
del x2['h - w']

In [43]:
x2

Name Relationship  Age Sex  Color  Lang.  Weight  height  h - w
0   Sathya       Spouse   37   F  White      1      65     160     95
1  Deeksha     Daughter   10   F   Dark      2      40     120     80
2   Thiyas          Son    1   M   Dark      3      10      90     80

In [97]:
x3=x2
x3

Name Relationship  Age Sex  Color  Lang.  Weight  height alpha
0   Sathya       Spouse   37   F  White      1      65     160     a
1  Deeksha     Daughter   10   F   Dark      2      40     120     b
2   Thiyas          Son    1   M   Dark      3      10      90     c

In [110]:
x3['alpha']=pd.Series(['a','b','c'])
x3

Name Relationship  Age Sex  Color  Lang.  Weight  height alpha
0   Sathya       Spouse   37   F  White      1      65     160     a
1  Deeksha     Daughter   10   F   Dark      2      40     120     b
2   Thiyas          Son    1   M   Dark      3      10      90     c

In [107]:
x4 = x3.set_index('alpha')
x4

Name Relationship  Age Sex  Color  Lang.  Weight  height
alpha                                                             
a       Sathya       Spouse   37   F  White      1      65     160
b      Deeksha     Daughter   10   F   Dark      2      40     120
c       Thiyas          Son    1   M   Dark      3      10      90

In [109]:
x4.drop('height',axis=1)

Name Relationship  Age Sex  Color  Lang.  Weight
alpha                                                     
a       Sathya       Spouse   37   F  White      1      65
b      Deeksha     Daughter   10   F   Dark      2      40
c       Thiyas          Son    1   M   Dark      3      10

In [112]:
x3

Name Relationship  Age Sex  Color  Lang.  Weight  height alpha
0   Sathya       Spouse   37   F  White      1      65     160     a
1  Deeksha     Daughter   10   F   Dark      2      40     120     b
2   Thiyas          Son    1   M   Dark      3      10      90     c

In [113]:
x4

Name Relationship  Age Sex  Color  Lang.  Weight  height
alpha                                                             
a       Sathya       Spouse   37   F  White      1      65     160
b      Deeksha     Daughter   10   F   Dark      2      40     120
c       Thiyas          Son    1   M   Dark      3      10      90

In [119]:
x5 = x4.append(x3)
x5

Name Relationship  Age Sex  Color  Lang.  Weight  height alpha
a   Sathya       Spouse   37   F  White      1      65     160   NaN
b  Deeksha     Daughter   10   F   Dark      2      40     120   NaN
c   Thiyas          Son    1   M   Dark      3      10      90   NaN
0   Sathya       Spouse   37   F  White      1      65     160     a
1  Deeksha     Daughter   10   F   Dark      2      40     120     b
2   Thiyas          Son    1   M   Dark      3      10      90     c

In [122]:
x5=x5.reset_index(drop=True)
x5

Name Relationship  Age Sex  Color  Lang.  Weight  height alpha
0   Sathya       Spouse   37   F  White      1      65     160   NaN
1  Deeksha     Daughter   10   F   Dark      2      40     120   NaN
2   Thiyas          Son    1   M   Dark      3      10      90   NaN
3   Sathya       Spouse   37   F  White      1      65     160     a
4  Deeksha     Daughter   10   F   Dark      2      40     120     b
5   Thiyas          Son    1   M   Dark      3      10      90     c

In [121]:
x5.fillna(0)

Name Relationship  Age Sex  Color  Lang.  Weight  height alpha
0   Sathya       Spouse   37   F  White      1      65     160     0
1  Deeksha     Daughter   10   F   Dark      2      40     120     0
2   Thiyas          Son    1   M   Dark      3      10      90     0
3   Sathya       Spouse   37   F  White      1      65     160     a
4  Deeksha     Daughter   10   F   Dark      2      40     120     b
5   Thiyas          Son    1   M   Dark      3      10      90     c

In [127]:
x5['alpha']=np.where(x5['Name']=='Sathya','f',x5['alpha'])

In [128]:
x5

Name Relationship  Age Sex  Color  Lang.  Weight  height alpha
0   Sathya       Spouse   37   F  White      1      65     160     f
1  Deeksha     Daughter   10   F   Dark      2      40     120   NaN
2   Thiyas          Son    1   M   Dark      3      10      90   NaN
3   Sathya       Spouse   37   F  White      1      65     160     f
4  Deeksha     Daughter   10   F   Dark      2      40     120     b
5   Thiyas          Son    1   M   Dark      3      10      90     c

In [133]:
x5['alpha']=np.where(x5['Name']=='Deeksha','a',x5['alpha'])
x5['alpha']=np.where(x5['Name']=='Thiyas','e',x5['alpha'])

In [134]:
x5

Name Relationship  Age Sex  Color  Lang.  Weight  height alpha
0   Sathya       Spouse   37   F  White      1      65     160     f
1  Deeksha     Daughter   10   F   Dark      2      40     120     a
2   Thiyas          Son    1   M   Dark      3      10      90     e
3   Sathya       Spouse   37   F  White      1      65     160     f
4  Deeksha     Daughter   10   F   Dark      2      40     120     a
5   Thiyas          Son    1   M   Dark      3      10      90     e

In [141]:
x6 = x5[['Age','Lang.','Weight','height','alpha']]
x6

Age  Lang.  Weight  height alpha
0   37      1      65     160     f
1   10      2      40     120     a
2    1      3      10      90     e
3   37      1      65     160     f
4   10      2      40     120     a
5    1      3      10      90     e

In [143]:
x6 = x6.rename(columns={'Lang.':'Language'})

In [144]:
x6

Age  Language  Weight  height alpha
0   37         1      65     160     f
1   10         2      40     120     a
2    1         3      10      90     e
3   37         1      65     160     f
4   10         2      40     120     a
5    1         3      10      90     e

In [135]:
pd.DataFrame(x5.describe())

Age     Lang.     Weight      height
count   6.000000  6.000000   6.000000    6.000000
mean   16.000000  2.000000  38.333333  123.333333
std    16.757088  0.894427  24.630604   31.411251
min     1.000000  1.000000  10.000000   90.000000
25%     3.250000  1.250000  17.500000   97.500000
50%    10.000000  2.000000  40.000000  120.000000
75%    30.250000  2.750000  58.750000  150.000000
max    37.000000  3.000000  65.000000  160.000000

In [151]:
x10=pd.DataFrame(np.random.randn(5,5),columns=['Col1','Col2','Col3','Col4','Col5'],index=['a','b','c','d','e'])

In [152]:
x10['Add']=x10['Col1']+x10['Col2']

In [158]:
x10

Col1      Col2      Col3      Col4      Col5       Add
a  1.118117  0.472345 -0.971895  0.334136  0.848258  1.590461
b  1.400323 -0.237072  0.032367  1.141983 -0.911634  1.163252
c  0.327491  0.971820 -0.203966  0.868550  0.103217  1.299312
d  1.830260 -0.046871 -1.990390 -0.980003 -1.631844  1.783389
e -0.109736 -0.849673 -0.136461  0.729433  0.083828 -0.959409

In [175]:
x5.set_index('alpha',inplace=True)

In [176]:
x5.sort_index()

Name Relationship  Age Sex  Color  Lang.  Weight  height
alpha                                                             
a      Deeksha     Daughter   10   F   Dark      2      40     120
a      Deeksha     Daughter   10   F   Dark      2      40     120
e       Thiyas          Son    1   M   Dark      3      10      90
e       Thiyas          Son    1   M   Dark      3      10      90
f       Sathya       Spouse   37   F  White      1      65     160
f       Sathya       Spouse   37   F  White      1      65     160

In [180]:
x1=x5.iloc[:3]

In [181]:
x2=x5.iloc[3:]

In [182]:
x1

Name Relationship  Age Sex  Color  Lang.  Weight  height
alpha                                                             
f       Sathya       Spouse   37   F  White      1      65     160
a      Deeksha     Daughter   10   F   Dark      2      40     120
e       Thiyas          Son    1   M   Dark      3      10      90

In [189]:
x2['Color']=x2['Color'].replace(['White','Dark','Dark'],['Blue','Green','Black'])

C:\Users\karthikp\AppData\Local\Temp/ipykernel_12184/1329409922.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  x2['Color']=x2['Color'].replace(['White','Dark','Dark'],['Blue','Green','Black'])


In [190]:
x2

Name Relationship    Age Sex  Color  Lang.  Weight  height
alpha                                                               
f       Sathya       Spouse   Blue   F   Blue      1      65     160
a      Deeksha     Daughter  Black   F  Black      2      40     120
e       Thiyas          Son  Black   M  Black      3      10      90

In [191]:
x3 = pd.merge(x1,x2, on='Name')

In [192]:
x3

Name Relationship_x  Age_x Sex_x Color_x  Lang._x  Weight_x  height_x  \
0   Sathya         Spouse     37     F   White        1        65       160   
1  Deeksha       Daughter     10     F    Dark        2        40       120   
2   Thiyas            Son      1     M    Dark        3        10        90   

  Relationship_y  Age_y Sex_y Color_y  Lang._y  Weight_y  height_y  
0         Spouse   Blue     F    Blue        1        65       160  
1       Daughter  Black     F   Black        2        40       120  
2            Son  Black     M   Black        3        10        90

In [200]:
df_left = pd.DataFrame({'Name':['Alex','Amy','Allen','Alice','Ayoung'], 
                        'id':[1,2,3,4,5], 
                        'SubjectId':['Sub1','Sub2','Sub4','Sub6','Sub7']})

df_right = pd.DataFrame({'Name':['Billy','Alice','Bran','Alex','Betty'],
                         'id':[1,2,3,4,5],
                         'SubjectId':['Sub2','Sub4','Sub3','Sub6','Sub5']})

In [194]:
df_left

Name  id SubjectId
0    Alex   1      Sub1
1     Amy   2      Sub2
2   Allen   3      Sub4
3   Alice   4      Sub6
4  Ayoung   5      Sub7

In [201]:
df_right

Name  id SubjectId
0  Billy   1      Sub2
1  Alice   2      Sub4
2   Bran   3      Sub3
3   Alex   4      Sub6
4  Betty   5      Sub5

In [206]:
x2 = pd.merge(df_left,df_right,on='Name',how='left')

In [207]:
x2

Name  id_x SubjectId_x  id_y SubjectId_y
0    Alex     1        Sub1   4.0        Sub6
1     Amy     2        Sub2   NaN         NaN
2   Allen     3        Sub4   NaN         NaN
3   Alice     4        Sub6   2.0        Sub4
4  Ayoung     5        Sub7   NaN         NaN

In [208]:
x2.fillna(0)

Name  id_x SubjectId_x  id_y SubjectId_y
0    Alex     1        Sub1   4.0        Sub6
1     Amy     2        Sub2   0.0           0
2   Allen     3        Sub4   0.0           0
3   Alice     4        Sub6   2.0        Sub4
4  Ayoung     5        Sub7   0.0           0

In [213]:
pd.concat([df_left,df_right],ignore_index=True)

Name  id SubjectId
0    Alex   1      Sub1
1     Amy   2      Sub2
2   Allen   3      Sub4
3   Alice   4      Sub6
4  Ayoung   5      Sub7
5   Billy   1      Sub2
6   Alice   2      Sub4
7    Bran   3      Sub3
8    Alex   4      Sub6
9   Betty   5      Sub5

### Python

In [221]:
var = range(1,50)
for i in var:
    if ( i%5==0):
        print(i)

5
10
15
20
25
30
35
40
45


In [222]:
def func():
    """ This is my first string"""
    print('Hi Everyone')

In [223]:
func()

Hi Everyone


In [224]:
print(func.__doc__)

 This is my first string


In [231]:
list1=list(range(1,100))
for i in list1:
    if i%10 == 0:
        print (i,end=", ")

10, 20, 30, 40, 50, 60, 70, 80, 90, 

In [234]:
[i for i in list1 if i%10==0]

[10, 20, 30, 40, 50, 60, 70, 80, 90]

In [235]:
list2 = ['Kartik','Kiran','Sathya','Sham','Deeksha','Deepa','Thiyash','Tom']
for i in list2:
    if i.startswith('K'):
        print(i)

Kartik
Kiran


In [236]:
[i for i in list2 if i.startswith('K')]

['Kartik', 'Kiran']

In [245]:
var1=[i for i in range(1,1000) if i%10==0 and break if i == 200]
print(var1,end="")

SyntaxError: invalid syntax (Temp/ipykernel_12184/430015655.py, line 1)

In [249]:
var2 = list(range(10,0,-1))
print(var2)

[10, 9, 8, 7, 6, 5, 4, 3, 2, 1]


In [253]:
var2 = [i**2 for i in range(6,0,-1)]
var2

[36, 25, 16, 9, 4, 1]

In [255]:
list1=list(range(0,30,3))
list1

[0, 3, 6, 9, 12, 15, 18, 21, 24, 27]

In [257]:
list1[3] = 90

In [258]:
list1

[0, 3, 6, 90, 12, 15, 18, 21, 24, 27]

In [259]:
list2 = tuple(range(0,30,3))
list2

(0, 3, 6, 9, 12, 15, 18, 21, 24, 27)

In [261]:
list2[5]=150

TypeError: 'tuple' object does not support item assignment

In [262]:
list3 = set(range(0,20,5))
list3

{0, 5, 10, 15}

In [266]:
list4 = {0,0,0,1,1,2,2,3,3,4,4,5}
list4

{0, 1, 2, 3, 4, 5}

In [267]:
int_var = int(340)
float_var = float(32.4)
convert1 = int_var + float_var
convert1

372.4

In [ ]:
num = int(input('Enter a number'))
if num > 0:
    print('Positive')
elif num == 0:
    print('Zero')
else:
    print('Negative')

In [ ]:
var1=[10,20,30,40]
add = 0

for i in var1:
    add = add+i
    print(i)

In [3]:
print('Hi')

Hi


In [6]:
i = 0
while i <=9:
    i = i+1
    print(i)

1
2
3
4
5
6
7
8
9
10


In [15]:
a = range(5)
for i in a:
    for j in range(5):
        print(j, end=" ")
        j=j+1
    print(i)
    i=i+1

0 1 2 3 4 0
0 1 2 3 4 1
0 1 2 3 4 2
0 1 2 3 4 3
0 1 2 3 4 4


In [16]:
row = 5
for i in range (1, row+1, 1):
    for j in range (1,i+1):
        print(j,end=" ")
    print()

1 
1 2 
1 2 3 
1 2 3 4 
1 2 3 4 5 


In [27]:
n=5
for i in range (n):
    for j in range (i+1):
        print('*', end=" ")
        j=j+1
    print()

* 
* * 
* * * 
* * * * 
* * * * * 


In [36]:
a=0
n=5
for i in range (1,n+1,1):
    a+=i
print(a)

15


In [2]:
list1 = [10,20,30,40]
add = 0

for i in list1:
    add = add + i
    print (add)

10
30
60
100


In [11]:
list2 = [50,60,70,80,90,100]

for i in list2:
    if i == 90:
        continue
    print(i)

50
60
70
80
100


In [ ]:
num = int(input('Enter a number : '))
i = 0 
s = 0

while i < 5:
    s = 0 + i
    print(i)

In [21]:
num = int(input('Enter a number : '))
i = 0 
s = 0

while i < num:
    s = s + i
    print(i)
    i = i +1
print(s)


Enter a number : 6
0
1
2
3
4
5
15


In [30]:
for i in 'Country':
    if i in 'n':
        continue
    print(i)

C
o
u
t
r
y


In [33]:
list3 = list(range(100,999,8))
print(list3,end=" ")

[100, 108, 116, 124, 132, 140, 148, 156, 164, 172, 180, 188, 196, 204, 212, 220, 228, 236, 244, 252, 260, 268, 276, 284, 292, 300, 308, 316, 324, 332, 340, 348, 356, 364, 372, 380, 388, 396, 404, 412, 420, 428, 436, 444, 452, 460, 468, 476, 484, 492, 500, 508, 516, 524, 532, 540, 548, 556, 564, 572, 580, 588, 596, 604, 612, 620, 628, 636, 644, 652, 660, 668, 676, 684, 692, 700, 708, 716, 724, 732, 740, 748, 756, 764, 772, 780, 788, 796, 804, 812, 820, 828, 836, 844, 852, 860, 868, 876, 884, 892, 900, 908, 916, 924, 932, 940, 948, 956, 964, 972, 980, 988, 996] 

In [47]:
n = range(1,8)
for i in n:
    if i/2:
        break

In [136]:
for i in range(6):
    for j in range(i):
        print("*",end=" ")
    print()
    
    


* 
* * 
* * * 
* * * * 
* * * * * 


In [148]:
for i in range(1,6):
    for j in range(5):
        print("*",end=" ")
    print()

* * * * * 
* * * * * 
* * * * * 
* * * * * 
* * * * * 


In [153]:
for i in range(1,6):
    for j in range(1,6):
        print(j,end=" ")
    print()

1 2 3 4 5 
1 2 3 4 5 
1 2 3 4 5 
1 2 3 4 5 
1 2 3 4 5 


In [162]:
for i in range(5,0,-1):
    for j in range(5):
        print(i,end=" ")
    print()

5 5 5 5 5 
4 4 4 4 4 
3 3 3 3 3 
2 2 2 2 2 
1 1 1 1 1 


In [176]:
for i in range(5,0,-1):
    for j in range(5,0,-1):
        print(j,end=" ")
    print()

5 4 3 2 1 
5 4 3 2 1 
5 4 3 2 1 
5 4 3 2 1 
5 4 3 2 1 


In [184]:
n = 5
k = 2

for i in range(1,n+1):
    for j in range(5):
        print(k,end=" ")
        k=k+2
    print()

2 4 6 8 10 
12 14 16 18 20 
22 24 26 28 30 
32 34 36 38 40 
42 44 46 48 50 


In [188]:
list_city = ['Chennai','Delhi','Mumbai']
for i in list_city:
    print('I love',i)

I love Chennai
I love Delhi
I love Mumbai


In [190]:
n = 0
for i in range(5):
    n = n+i
print(n)

10


In [194]:
i = 5
n = 0
s = 0

while n<i:
    s=s+n
    n = n+1
print(s)

10


In [197]:
def greet():
    print('Hi')
    print('Good Morning')

In [198]:
greet()

Hi
Good Morning


In [207]:
def add_sub (x,y):
    c = x+y
    d = x-y
    return c,d

result=add_sub(5,10)

In [208]:
result

(15, -5)

In [218]:
def value(k):
    if k > 0:
        print(k)
    else:
        k = k*-1
        print(k)
    

In [219]:
value(-9)

9


In [220]:
def greet (x,y='Good Morning'):
    print(x,y)

In [221]:
greet ('Hi')

Hi Good Morning


In [222]:
greet ( 'Hello','Everone')

Hello Everone


In [223]:
greet('Hello')

Hello Good Morning


In [226]:
def recursion(x):
    if x ==1:
        return x
    else:
        return ( x * recursion(x-1))
    
num = 5

recursion(num)

120

In [229]:
def var(x,y):
    a = x+y
    b = x-y
    c = x*y
    print('Value of addition is:',a)
    print('Value of Subtraction is:',b)
    print('Value of Multiplication is: ',c)

In [230]:
var(12,18)

Value of addition is: 30
Value of Subtraction is: -6
Value of Multiplication is:  216


In [234]:
def roll_no(x):
    a=[20,30,40,50,60]
    if x in a:
        print('Roll #',x,'is present')
    else:
        print('Roll #',x,'is absent')
    

In [236]:
roll_no(21)

Roll # 21 is absent


In [244]:
def maxi(x,y,z):
    if x>y and x>z:
        return x
    elif y>x and y>z:
        return y
    else:
        print(z)

In [248]:
maxi(6,8,9)

9


In [253]:
def form(x):
    if x%2==0:
        print('Entered # is Even')
    else:
        print('Enetere # is Odd')

In [254]:
form(10)

Entered # is Even


In [266]:
a = list(filter(lambda x : x%2==0, range(10)))
print(a)

[0, 2, 4, 6, 8]


In [269]:
b = list(map(lambda x : x%2, range(10)))
print(b)

[0, 1, 0, 1, 0, 1, 0, 1, 0, 1]


In [272]:
var = 10

def var1(x):
    y=x+var
    print(y)
    
var1(20)
print(var)

30
10


In [273]:
nested_list = [[1,2,3],[4,5,6],['Seven','Eight','Nine']]
nested_list

[[1, 2, 3], [4, 5, 6], ['Seven', 'Eight', 'Nine']]

In [274]:
nested_list[2]

['Seven', 'Eight', 'Nine']

In [275]:
nested_list[2][1]

'Eight'

In [276]:
nested_list[-2][-2]

5

In [281]:
list1=[1,2,3]
list2=[4,5,6]
list3=['Seven','Eight','Nine']
list1.append(list2)
print(list1)

[1, 2, 3, [4, 5, 6]]


In [283]:
list1.append(list3)
print(list1)

[1, 2, 3, [4, 5, 6], ['Seven', 'Eight', 'Nine'], ['Seven', 'Eight', 'Nine']]


In [285]:
list1[5]

['Seven', 'Eight', 'Nine']

In [287]:
print(list1+list2)

[1, 2, 3, [4, 5, 6], ['Seven', 'Eight', 'Nine'], ['Seven', 'Eight', 'Nine'], 4, 5, 6]


In [298]:
str1=('DataScience')
vow =('a','e','i','0','u')

for i in str1:
    if i == ('a'):
        continue
    print(i)

D
t
S
c
i
e
n
c
e


In [301]:
for i in range(10):
    i = i*i
    print(i,end=", ")

0, 1, 4, 9, 16, 25, 36, 49, 64, 81, 

In [303]:
[i**2 for i in range(10)]

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]

In [308]:
for i in enumerate(('India','USA','Russia'),100):
    print(i)

(100, 'India')
(101, 'USA')
(102, 'Russia')


In [309]:
tupl1 = (1,2,[3,4,5])
tupl1

(1, 2, [3, 4, 5])

In [312]:
tupl1[1]=6
tupl1

TypeError: 'tuple' object does not support item assignment

In [316]:
my_list = ['K','S','D','T']
my_iter = iter(my_list)
print(next(my_iter))
print(next(my_iter))
print(next(my_iter))

K
S
D


In [326]:
def Squaring(nums):
    for i in nums:
        yield(i*i)

In [327]:
x=Squari
ng([1,2,3])

In [328]:
next(x)

1

In [329]:
next(x)

4

In [330]:
next(x)

9

In [356]:
def func5(st):
    l=len(st)
    for i in range(l-1,0,-1):
        yield st[i]

str1='Data Science'
str2=func5(str1)
print(next(str2))
print(next(str2))
print(next(str2))
print(next(str2))
print(next(str2))
#print(next(func5(str1))
#print(next(func5(str1))
#print(next(func5(str1))



e
c
n
e
i


In [359]:
def rev_str(x):
    l=len(x)
    for i in range (l-1,-1,-1):
        print(x)
        
print(rev_str('DataScience'))

DataScience
DataScience
DataScience
DataScience
DataScience
DataScience
DataScience
DataScience
DataScience
DataScience
DataScience
None


In [368]:
var2 = 'DataScience'
l=len(var2)
for i in range(l-1,0,1):
    print(var2[i])

In [364]:
text = 'Hello World'[::-1]
text

'dlroW olleH'