In [1]:
import numpy as np

In [4]:
a=np.array([[1,2,3],[4,5,6]])
y=np.array([[3,4,5],[3,3,3]])
print(a)
print(y)

[[1 2 3]
 [4 5 6]]
[[3 4 5]
 [3 3 3]]


In [5]:
np.stack((a,y),axis=0)

array([[[1, 2, 3],
        [4, 5, 6]],

       [[3, 4, 5],
        [3, 3, 3]]])

In [6]:
np.stack((a,y),axis=1)

array([[[1, 2, 3],
        [3, 4, 5]],

       [[4, 5, 6],
        [3, 3, 3]]])

In [7]:
np.vstack((a,y))

array([[1, 2, 3],
       [4, 5, 6],
       [3, 4, 5],
       [3, 3, 3]])

In [8]:
np.hstack((a,y))

array([[1, 2, 3, 3, 4, 5],
       [4, 5, 6, 3, 3, 3]])

In [10]:
a = np.arange(9)
np.split(a,3)

[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8])]

In [17]:
x=([[2,3,4],[3,4,5]])
#y=([[4,5,6],[7,8,9]])
np.append(x,[[20,30,40]],axis=0)

array([[ 2,  3,  4],
       [ 3,  4,  5],
       [20, 30, 40]])

In [16]:
x=([[2,3,4],[3,4,5]])
#y=([[4,5,6],[7,8,9]])
np.append(x,[[20,30,40]],axis=1)

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 2 and the array at index 1 has size 1

In [19]:
x=([[2,3,4],[3,4,5]])
#y=([[4,5,6],[7,8,9]])
np.append(x,[[20,30,40],[100,200,300]],axis=1)

array([[  2,   3,   4,  20,  30,  40],
       [  3,   4,   5, 100, 200, 300]])

In [29]:
x=([[2,3,4],[3,4,5],[5,6,7]])
#y=([[4,5,6],[7,8,9]])
np.insert(x,1,1,1)

array([[2, 1, 3, 4],
       [3, 1, 4, 5],
       [5, 1, 6, 7]])

In [34]:
x=([[2,3,4],[3,4,5],[5,6,7]])
x
np.delete(x,1,0)

array([[2, 3, 4],
       [5, 6, 7]])

In [36]:
x=([[2,3,4],[3,4,5],[5,6,7],[10,20,30],[40,50,60]])
x
#y=([[4,5,6],[7,8,9]])
#np.insert(x,1,1,1)

[[2, 3, 4], [3, 4, 5], [5, 6, 7], [10, 20, 30], [40, 50, 60]]

In [37]:
np.stack(x)

array([[ 2,  3,  4],
       [ 3,  4,  5],
       [ 5,  6,  7],
       [10, 20, 30],
       [40, 50, 60]])

In [64]:
np.delete(x,0,1)

array([[ 3,  4],
       [ 4,  5],
       [ 6,  7],
       [20, 30],
       [50, 60]])

In [74]:
x1=[[1,1,2,3],[5,5,6,7]]
x2=[[3,4,5,6],[7,8,9,10]]
add=np.add(x1,x2)
mul=np.multiply(x1,x2)
sub=np.subtract(x1,x2)
div=np.divide(x1,x2)
print('The value for addition',add)
print('The value for mul', mul)
print('The value for sub', sub)
print('The value for div',div)

The value for addition [[ 4  5  7  9]
 [12 13 15 17]]
The value for mul [[ 3  4 10 18]
 [35 40 54 70]]
The value for sub [[-2 -3 -3 -3]
 [-2 -3 -3 -3]]
The value for div [[0.33333333 0.25       0.4        0.5       ]
 [0.71428571 0.625      0.66666667 0.7       ]]


In [75]:
np.power?

In [76]:
array1=np.arange(6)
np.power(array1,3)

array([  0,   1,   8,  27,  64, 125], dtype=int32)

In [77]:
np.percentile?

In [78]:
np.mean?

In [83]:
x1=np.array([[1,1,2,3],[5,5,6,7]])
#x2=[[3,4,5,6],[7,8,9,10]]
np.mean(x1,axis=0)

array([3., 3., 4., 5.])

In [84]:
x1

array([[1, 1, 2, 3],
       [5, 5, 6, 7]])

### Pandas

In [85]:
import pandas as pd

In [88]:
a=np.array([10,2,50,70])
s=pd.Series(a)

In [87]:
type(a)

numpy.ndarray

In [89]:
s

0    10
1     2
2    50
3    70
dtype: int32

In [90]:
a=np.array([10,2,50,70])
s=pd.Series(a, index=[1.,2,3.,4.])
s

1.0    10
2.0     2
3.0    50
4.0    70
dtype: int32

In [91]:
len(a)

4

In [92]:
list(range(len(a)))

[0, 1, 2, 3]

In [93]:
list(range(1,(len(a),10)))

TypeError: 'tuple' object cannot be interpreted as an integer

In [95]:
dict1={1:'Val1',2:'Val2',3:'Val3'}
s=pd.Series(dict1)
s

1    Val1
2    Val2
3    Val3
dtype: object

In [104]:
dict1={1:'Val1',2:'Val2',3:'Val3'}
s=pd.Series(dict1,index=[3,1,2])
s

3    Val3
1    Val1
2    Val2
dtype: object

In [113]:
x1=np.array([1,2,3,4,5])
y1=pd.Series(x1,index=[10,11,12,13,14])

In [114]:
y1

10    1
11    2
12    3
13    4
14    5
dtype: int32

In [14]:
`

1
2
3
4


In [15]:
def sum_list(n):
    if n ==1:
        return n
    else:
        return n+sum_list(n-1)        

In [17]:
print('The sum of given # is', sum_list(5))

The sum of given # is 15


In [28]:
x2=range(1,20,3)
for i in x2:
    total = i+(i-1)
print(total)

37


In [32]:
def sum_list1(data_list):
    total = 0
    for i in data_list:
        print(i)
#        if type(i)==type([]):
#            total = total + sum_list1(i)
#        else:
#            total = total + i
#    return total

In [33]:
sum_list1([1,2,3,[4,5],3,[6,7]])

1
2
3
[4, 5]
3
[6, 7]


In [49]:
def factorial(n):
    if n<=1:
        return 1
    else:
        return n*(factorial5(n-1))

In [50]:
print(factorial5(5))

120


In [1]:
my_list = list(range(10))

In [7]:
fil = list(filter(lambda x : x%2 == 0, my_list))
print(fil)

[0, 2, 4, 6, 8]


In [8]:
my_list1 = list(range(10))
fil1=list(filter(lambda x : x%2==1, my_list1))
print(fil1)

[1, 3, 5, 7, 9]


In [18]:
my_list1=list(range(10))
for i in my_list1:
    if i%2 == 1:
        print(i)

1
3
5
7
9


In [23]:
my_list2 = list([1,2,3,4,5,6])
map1 = list(map(lambda x: x%2,my_list2))
print(map1)

[1, 0, 1, 0, 1, 0]


In [26]:
my_list3 = list(range(1, 20, 3))
map2 = list(map(lambda x: x%5,my_list3))
print(map2)

[1, 4, 2, 0, 3, 1, 4]


In [31]:
def fun(var):
    letters = ['K','A','R','T','I','K']
    if var in letters:
        return True
    else:
        return False

seq = ['A','B','K','T']
fil = list(filter(fun,seq))
print(fil)

['A', 'K', 'T']


In [32]:
var = 20

def func():
    y = 10
    global var
    x = y*var
    print(x)

In [33]:
func()

200


In [35]:
nested_list = [1,2,3,[4,5,6],[7,8,9]]
nested_list

[1, 2, 3, [4, 5, 6], [7, 8, 9]]

In [36]:
nested_list[2
           ]

3

In [37]:
nested_list[4]

[7, 8, 9]

In [38]:
nested_list[4][2]

9

In [39]:
nested_list[-2][0]

4

In [42]:
list1=[1,2,3]
list1.append([4,5,6])
list1

[1, 2, 3, [4, 5, 6]]

In [43]:
list1.extend([7])
list1

[1, 2, 3, [4, 5, 6], 7]

In [52]:
var = [9,10,11]
list1.insert(2,var)
list1

[[9, 10, 11],
 [9, 10, 11],
 [9, 10, 11],
 [9, 10, 11],
 1,
 [9, 10, 11],
 [9, 10, 11],
 [9, 10, 11],
 [9, 10, 11],
 2,
 3,
 [4, 5, 6],
 7]

In [53]:
list2=[2,3,4,5]

In [58]:
list2.insert(6,1)

In [59]:
list2

[2, 3, 1, 1, 4, 5, 1]

In [60]:
list2.remove(1)
list2

[2, 3, 1, 4, 5, 1]

In [61]:
list2.remove(1)
list2

[2, 3, 4, 5, 1]

In [62]:
list2.remove(1)
list2

[2, 3, 4, 5]

In [63]:
list2.remove(1)
list2

ValueError: list.remove(x): x not in list

In [71]:
list2.pop(1
         )

IndexError: pop index out of range

In [70]:
list2

[2]

In [72]:
list3=[1,2,3,4,5,6,7,8,9]
list3.pop(3)

4

In [73]:
list3

[1, 2, 3, 5, 6, 7, 8, 9]

In [74]:
list3.pop(6)

8

In [75]:
list3

[1, 2, 3, 5, 6, 7, 9]

In [76]:
list3.index(6)

4

In [77]:
list3.count(i)

1

In [78]:
list3

[1, 2, 3, 5, 6, 7, 9]

In [86]:
x1=list((enumerate(list3,10)))
x1

[(10, 1), (11, 2), (12, 3), (13, 5), (14, 6), (15, 7), (16, 9)]

In [89]:
my_list1=[1,2,3,4,5]
x2 = iter(my_list1)
print(next(x2))
print(next(x2))
print(next(x2))
print(next(x2))

1
2
3
4


In [101]:
def gen_func():
    num=1
    print('1st #')
    yield(num)
    num=+1
    print('2nd #')
    yield(num)
    num=+1
    print('3rd #')
    yield(num)

In [102]:
var = gen_func()

In [103]:
print(next(var))

1st #
1


In [104]:
print(next(var))

2nd #
1


In [107]:
def generator_func1():
    for i in range(10):
        print("hi")
        yield i

In [109]:
var2=generator_func1()
print(next(var2))

hi
0


In [110]:
x2=list(range(10))
x2

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [114]:
x2=list(range(9,0,-1))
x2

[9, 8, 7, 6, 5, 4, 3, 2, 1]

In [115]:
x3=reverse(x2)

NameError: name 'reverse' is not defined

In [121]:
list4=[2,3,4,5]
[i**3 for i in list4]

[8, 27, 64, 125]

In [126]:
gen_exp=(i**4 for i in list4)
print(next(gen_exp))
print(next(gen_exp))
print(next(gen_exp))
print(next(gen_exp))

16
81
256
625


In [128]:
min(i**4 for i in list4)

16

In [129]:
def outer_fun(arg):
    var=5
    def inner_fun():
        var1=arg*5+var
        print(var1)
    inner_fun()

In [137]:
def outer_fun(arg):
    var3 = 5
    def inner_fun():
        var1 = arg * 5 + var3
        var2 = 5
    print(var2)
#        return var2
    return inner_fun()

In [139]:
import numpy as np

In [140]:
x1 = ([3, 5], [5, 4], [6, 7])
np.array(x1)

array([[3, 5],
       [5, 4],
       [6, 7]])

In [143]:
a1 = np.asarray(x1,dtype=float)
a1

array([[3., 5.],
       [5., 4.],
       [6., 7.]])

In [1]:
import pandas as pd
import numpy as py

In [3]:
list1=list(range(5))
df = pd.DataFrame(list1)
print(df)

   0
0  0
1  1
2  2
3  3
4  4


In [8]:
list2 =[[1,2],[3,4],[5,6]]
df1 = pd.DataFrame(list2,columns=['x1','x2'])

In [9]:
df1

x1  x2
0   1   2
1   3   4
2   5   6

In [6]:
list3=[['abc',1],['cde',2]]
df1=pd.DataFrame(list3,columns=['name','#'])
df1

name  #
0  abc  1
1  cde  2

In [11]:
d1 = {'CSK':[1,2,3],'RCB':[2,1,2]}
dataf2 = pd.DataFrame(d1)
dataf2

CSK  RCB
0    1    2
1    2    1
2    3    2

In [13]:
d1 = {'CSK':[1,2,3],'RCB':[2,1,2]}
dataf2 = pd.DataFrame(d1,index=[1,2,3])
dataf2

CSK  RCB
1    1    2
2    2    1
3    3    2

In [ ]:
aaa